- hosts: all
  tasks:
    - name: install package
      yum:
        name: "{{ package_name }}"
        state: "{{ package_state }}"

    - name: add stuff to hosts
      lineinfile:
        path: /etc/hosts
        regexp: '^127\.0\.0\.1'
        line: 127.0.0.1 localhost
        owner: root
        group: root
        mode: '0644'
